version: '3.8'

services:
  web:
    build: .
    image: laravelcompanyprofile
    container_name: laravelcompanyprofile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel-company-profile
    volumes:
      - ./:/var/www/laravel-company-profile
      - ./storage/docker/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ../storage/app:/var/www/laravel-company-profile/storage/app
    networks:
      - laravelcompanyprofile
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravelcompanyprofile_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/laravel-company-profile
      - ./storage/docker/:/etc/nginx/conf.d/
    networks:
      - laravelcompanyprofile

  db:
    image: mysql:5.7
    container_name: laravelcompanyprofile_db
    restart: unless-stopped
    tty: true
    ports:
      - "8306:3306"
    environment:
      MYSQL_USER: compro
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: compro_db
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravelcompanyprofile

networks:
  laravelcompanyprofile:
    driver: bridge

volumes:
  dbdata:
    driver: local
